//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitaplon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemthi
    {
        public int MaMH { get; set; }
        public double DiemThi1 { get; set; }
        public string Monhoc { get; set; }
        public int MaSV { get; set; }
    
        public virtual sinhvien sinhvien { get; set; }
    }
}
