//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitaplon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giangvien
    {
        public int MaGV { get; set; }
        public string TenGV { get; set; }
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public Nullable<int> MaKhoa { get; set; }
    
        public virtual khoa khoa { get; set; }
    }
}
