//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitaplon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class giangvien
    {
        public int MaGV { get; set; }
        [Required(ErrorMessage = "Họ tên là bắt buộc.")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Họ tên phải có từ 10 đến 50 ký tự.")]
        public string TenGV { get; set; }
        [Required(ErrorMessage = "Mật khẩu là bắt buộc.")]
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        [Required(ErrorMessage = "Số điện thoại là bắt buộc.")]
        [RegularExpression(@"^(090|098|091|031|035|038)\d{7}$", ErrorMessage = "Số điện thoại phải là chuỗi số có 10 ký tự và bắt đầu bằng 090, 098, 091, 031, 035 hoặc 038.")]
        public string SDT { get; set; }
        public Nullable<int> MaKhoa { get; set; }
    
        public virtual khoa khoa { get; set; }
    }
}
