//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitaplon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinhvien()
        {
            this.diemthi = new HashSet<diemthi>();
        }
    
        public int MaSV { get; set; }
        [Required(ErrorMessage = "Họ tên là bắt buộc.")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Họ tên phải có từ 10 đến 50 ký tự.")]
        public string TenSV { get; set; }
        [Required(ErrorMessage = "Mật khẩu là bắt buộc.")]
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        [Required(ErrorMessage = "Số điện thoại là bắt buộc.")]
        [RegularExpression(@"^(090|098|091|031|035|038)\d{7}$", ErrorMessage = "Số điện thoại phải là chuỗi số có 10 ký tự và bắt đầu bằng 090, 098, 091, 031, 035 hoặc 038.")]
        public string SDT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public Nullable<int> MaLop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diemthi> diemthi { get; set; }
        public virtual lop lop { get; set; }
    }
}
